services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # command: jupyter-lab --ip 0.0.0.0 --port=8080 --allow-root --no-browser
    working_dir: "/app"
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/app